# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('number', models.IntegerField(blank=1, null=1)),
            ],
            options={
                'db_table': 'soccer_fields',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['time'],
                'db_table': 'soccer_games',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'soccer_leagues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'soccer_organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iscurrent', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_schedules.Organization')),
            ],
            options={
                'db_table': 'soccer_seasons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('color', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='game_schedules.League')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('roster', models.ManyToManyField(related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'db_table': 'soccer_teams',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='league',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='game_schedules.Organization'),
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='game_schedules.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'league', chained_model_field=b'league', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='game_schedules.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_schedules.Field'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'league', chained_model_field=b'league', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='game_schedules.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_schedules.League'),
        ),
        migrations.AddField(
            model_name='field',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_schedules.Organization'),
        ),
    ]
