# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
