# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='number',
            field=models.IntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_schedules.Field'),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
