# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0002_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='breakaway_word_file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
