# Generated by Django 2.0.3 on 2018-03-25 18:31

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0003_league_breakaway_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='motto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='league', chained_model_field='league', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='game_schedules.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='league', chained_model_field='league', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='game_schedules.Team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='breakaway_word_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
