# Generated by Django 2.0.3 on 2018-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0004_auto_20180325_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
