# Generated by Django 2.0.3 on 2018-12-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0005_organization_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='breakaway_import_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
