# Generated by Django 2.0.3 on 2018-12-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0006_league_breakaway_import_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='key',
        ),
    ]
