# Generated by Django 2.0.3 on 2018-12-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0007_remove_league_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='number',
        ),
        migrations.AddField(
            model_name='field',
            name='identifier',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
