# Generated by Django 2.1.4 on 2019-05-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0008_auto_20181218_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='league',
            name='sheets_games_named_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='sheets_teams_named_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='team_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        )
    ]
