# Generated by Django 2.1.4 on 2019-05-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0009_auto_20190517_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
