# Generated by Django 2.2.1 on 2019-08-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_schedules', '0012_auto_20190815_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
